
language: python
python:
  - "2.7"

addons:
    apt:
        packages:
          - python-dev
          - python-pip
          - cmake

sudo: false

compiler:
  - gcc

before_install:
  - ./dev/scripts/setup-tests
install:
  - true
script:
  - ./dev/scripts/configure-project
  - ./dev/scripts/run-tests

