#! /usr/bin/env bash

set -e
cd "$( dirname "$( dirname "$( dirname "$0" )" )" )"

echo ""
echo "PREPARING ENVIRONMENT"
echo ""

source "dev/include/test-env.bash"

$APT_SUDO apt-get update
$APT_SUDO apt-get install -qyy python-dev python-pip cmake
if [ "$FULL_VIRTUALIZATION" '=' "YES" ] ; then
    $APT_SUDO apt-get install -qyy vagrant
fi
$PIP_SUDO pip install -U pip
$PIP_SUDO pip install -U setuptools
$PIP_SUDO pip install -U ansible             \
                         boto                \
                         coverage            \
                         flake8              \
                         pep8                \
                         flake8-docstrings   \
                         flake8-blind-except

